[package]
name = "tree_sitter_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
tree-sitter = "0.20.9"

[build-dependencies]
cc="1.0"
